version: '2'
services:
    postgres:
        extends:
            file: postgresql.yml
            service: postgres
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
    redis:
        container_name: redis
        image: redis:latest
        ports:
        - 6379:6379

