version: '2'

services:
    keycloak:
        image: jboss/keycloak:4.5.0.Final

        ## comment the following lines if keycloak is to run in the mode to export realm and users
        #command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=IGNORE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
        #volumes:
        #- ./realm-config:/opt/jboss/keycloak/realm-config

        ## uncomment the following command if keycloak is run in the mode to export realm and users. realm and users are exported to ~/volumes/dega/keycloak/realm-config directory
        command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
        volumes:
        - ~/volumes/dega/keycloak/realm-config:/opt/jboss/keycloak/realm-config

        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
        - 9080:9080
